[package]
name = "fetchchromium"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"] }
serde = { version = "1.0.152", features = ["serde_derive"] }
serde_json = "1.0"
